import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {AiFillTwitterCircle, AiFillLinkedin, AiFillYoutube, AiFillMail} from 'react-icons/ai'
import Image from 'next/image'
import ylogo from '../public/logo-dale.png'
import design from '../public/design.png'
import code from '../public/code.png'
import consulting from '../public/consulting.png'
import web1 from '../public/web1.png'
import web2 from '../public/web2.png'
import web3 from '../public/web2.png'
import web4 from '../public/web2.png'
import web5 from '../public/web2.png'
import web6 from '../public/web2.png'
import web7 from '../public/web2.png'
import {useState} from 'react'

export default function Home() {
  const [darkMode, setDarkMode] = useState(false)
  return (
    <div className={darkMode ? 'dark': ""}>
      <Head>
        <title>Yusuf K. Muhammad</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-800" >
        <section className="min-h-screen">

        <nav className="py-10 mb-12 flex justify-between">
          <h1 className="text-xl font-burtons dark:text-teal-500">Yusuf K. Muhammad</h1>
          <ul className="flex items-center">
            <li><BsFillMoonStarsFill className="cursor-pointer text-xl dark:text-white" onClick={()=>setDarkMode(!darkMode)} /></li>
            <li><a href="#" className="bg-gradient-to-r from-cyan-500 to-teal-500  bg-cyan-500 text-white px-4 py-2 rounded-md ml-8">Resume</a></li>
          </ul>
        </nav>

        <div className="text-center px-10 py-5">
          <h2 className="text-5xl py-2 text-teal-500 font-medium md:text-6xl font-burtons">Yusuf K. Muhammad</h2>
          <h3 className="text-2xl py-2 md:text-3xl dark:text-blue-100">Engineer and Artisan</h3>
          <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto dark:text-blue-100">
            Freelance providing services for programming needs. Let&apos;s talk to help you ahieve your goals.
          </p>
        </div>
        <div className="relative mx-auto bg-gradient-to-b from-teal-500  rounded-full w-80 h-80 mb-10 overflow-hidden md:h-96 md:w-96">
          <Image src={ylogo} fill className="rounded-full" alt={''}/>
        </div>

        <div className="text-4xl flex justify-center gap-16 pb-10 text-gray-600 dark:text-white">
          <AiFillTwitterCircle/>
          <AiFillLinkedin />
          <AiFillYoutube />
          <AiFillMail />
        </div>

        </section>
        {/* comment */}

        <section className="text-gray-800 dark:text-teal-100">
          <div className="">
            <h3 className="text-3xl py-1 max-w-xl mx-auto font-burtons"> Services I Offer</h3>
            <p className="text-md py-2 leading-8 max-w-xl mx-auto">
            As a freelance web developer and designer, I offer a range of services to help businesses and individuals bring their visions to life online. With a focus on user experience and modern design, I create websites that are not only visually appealing, but also functional and easy to use.
            </p>
          </div>
          <div className="lg:flex gap-10 justify-center">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 text-gray-800 dark:shadow-teal-500 dark:text-teal-50" >
              <Image src={design} width={100} height={100} alt={''} />
              <h3 className="text-lg font-medium pt-8 pb-2">Beautiful Design</h3>
              <p className="py-2">I create websites that are not only visually appealing, but also functional and easy to use.</p>
              <h4 className="py-4 font-black">Tools i used</h4>
              <p className="py-1">Inkscape</p>
              <p className="py-1">Figma</p>
            </div>

            <div className="text-center shadow-lg p-10 rounded-xl my-10" >
              <Image src={code} width={100} height={100} alt={''} />
              <h3 className="text-lg font-medium pt-8 pb-2">Apps</h3>
              <p className="py-2">I create websites that are not only visually appealing, but also functional and easy to use.</p>
              <h4 className="py-4 text-teal-600">Tools i used</h4>
              <p className="text-gray-800 py-1">Inkscape</p>
              <p className="text-gray-800 py-1">Figma</p>
            </div>

            <div className="text-center shadow-lg p-10 rounded-xl my-10" >
              <Image src={consulting} width={100} height={100} alt={''} />
              <h3 className="text-lg font-medium pt-8 pb-2">Consulting</h3>
              <p className="py-2">I create websites that are not only visually appealing, but also functional and easy to use.</p>
              <h4 className="py-4 text-teal-600">Tools i used</h4>
              <p className="text-gray-800 py-1">Inkscape</p>
              <p className="text-gray-800 py-1">Figma</p>
            </div>
          </div>

        </section>

        <section className="text-gray-800 dark:text-teal-100">
        <div>
            <h3 className="text-3xl py-1 max-w-xl mx-auto font-burtons">My Works</h3>
            <p className="text-md py-2 leading-8 text-gray-80 max-w-xl mx-auto">
            As a web developer and designer with years of experience, I am passionate about creating beautiful and functional websites that help businesses and individuals achieve their goals online. With a focus on user experience and modern design, I strive to deliver high-quality products that not only look great, but are also easy to use and navigate.
            </p>

            <p className="text-md py-2 leading-8 text-gray-80 max-w-xl mx-auto">
            I offer services to create your product or websites, and also teach and guide you.
            </p>
          </div>

          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/4 flex-1">
              <Image src={web1} alt={''} className="rounded-lg object-cover" />
              <p>Samsat Provinsi Kalimantan Timur</p>
            </div>
            <div className="basis-1/4 flex-1">
              <Image src={web2} alt={''} className="rounded-lg object-cover" />
            </div>
            <div className="basis-1/4 flex-1">
              <Image src={web3} alt={''} className="rounded-lg object-cover" />
            </div>
            <div className="basis-1/4 flex-1">
              <Image src={web4} alt={''} className="rounded-lg object-cover" />
            </div>
            <div className="basis-1/4 flex-1">
              <Image src={web5} alt={''} className="rounded-lg object-cover" />
            </div>
            <div className="basis-1/4 flex-1">
              <Image src={web6} alt={''} className="rounded-lg object-cover" />
            </div>
            <div className="basis-1/4 flex-1">
              <Image src={web7} alt={''} className="rounded-lg object-cover" />
            </div>
          </div>

        </section>

      </main>

      
    </div>
  )
}
